### ISSUE TITLE
Problem evaluation classifier: Java executable could not be found

### ISSUE THREAD

**Issue by arkantos91** [larskotthoff/autoweka#37]
I'm using latest version of Weka and I downloaded Auto Weka 2.3 with Weka Package Manager.

Now when I select the AutoWeka Classifier and click start, I get Problem evaluation classifier: Java executable could not be found.

I'm on Windows 10.

Of course I have JRE and JDK installed and no other issues running other stuff requiring them (i.e. Eclipse).

What should I do?

Thanks

**Comment by larskotthoff** [comment]
Can you provide the complete log output please?

**Comment by arkantos91** [comment]
Here you go

`18:09:04: Weka Explorer
18:09:04: (c) 1999-2016 The University of Waikato, Hamilton, New Zealand
18:09:04: web: http://www.cs.waikato.ac.nz/~ml/weka/
18:09:04: Started on lunedì, 6 marzo 2017
18:09:19: Base relation is now direction_Ortu_comments_NFDA-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.StringToWordVector-R2-W10000000-prune-rate-1.0-T-I-N1-stemmerweka.core.stemmers.NullStemmer-stopwords-handlerweka.core.stopwords.Null-M1-tokenizerweka.core.tokenizers.NGramTokenizer -max 2 -min 1 -delimiters " \r\n\t.,;:\'\"()?!" (723 instances)
18:09:25: java.lang.NullPointerException
18:09:42: Started weka.classifiers.meta.AutoWEKAClassifier
18:09:42: Command: weka.classifiers.meta.AutoWEKAClassifier -seed 123 -timeLimit 15 -memLimit 1024 -nBestConfigs 1 -metric errorRate -parallelRuns 1
18:09:46: Java executable could not be found. Please refer to "Known Issues" in the Auto-WEKA manual.`

**Comment by larskotthoff** [comment]
Thanks, I'll have a look.

**Comment by nikoskr** [comment]
Hello Lars,
Please consider my case on the same issue if possible. 
The machine runs on Windows 7, Weka 3-8, Autoweka 2.3 (installed thru the Package Manager). 
As I failed to run AutoWeka on WEKA GUI, I tried to run it from the command line as follows:
C:\Users\nikos\wekafiles\packages\Auto-WEKA>java -classpath "%CLASSPATH%"  weka.
classifiers.meta.AutoWEKAClassifier -t train.arff -timeLimit 15 -no-cv
 07, 2017 5:47:04  com.github.fommil.netlib.ARPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemARPACK
07, 2017 5:47:04  com.github.fommil.netlib.ARPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeRefARPACK
java.lang.Exception: Java executable could not be found. Please refer to "Known
Issues" in the Auto-WEKA manual.
        at weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClas
sifier.java:346)
        at weka.classifiers.evaluation.Evaluation.evaluateModel(Evaluation.java:
1529) at weka.classifiers.Evaluation.evaluateModel(Evaluation.java:650)
        at weka.classifiers.AbstractClassifier.runClassifier(AbstractClassifier.
java:141)
        at weka.classifiers.meta.AutoWEKAClassifier.main(AutoWEKAClassifier.java
:265)

C:\Users\nikos\wekafiles\packages\Auto-WEKA>java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

C:\Users\nikos\wekafiles\packages\Auto-WEKA>echo %classpath%
C:\Program Files\Weka-3-8\weka.jar;C:\Program Files\Java\jre1.8.0_45\bin\javaw.j
ar;C:\Program Files\Java\jdk1.7.0_79\bin\java.jar;C:\Users\nikos\wekafiles\packa
ges\Auto-WEKA\autoweka.jar

Many thanks for your efforts.
Nikos

**Comment by s3312345** [comment]
I"ve also had the same Java executable not found error as arkantos91. Also running Windows 10 (Home).

**Comment by larskotthoff** [comment]
This is fixed in 2.4, which should be available shortly.

**Comment by nikoskr** [comment]
Many thanks.
