### ISSUE TITLE
Java executable could not be found. Please refer to "Known Issues" in the Auto-WEKA manual.

### ISSUE THREAD

**Issue by jiyonghe** [larskotthoff/autoweka#38]
java.lang.Exception: Java executable could not be found. Please refer to "Known
Issues" in the Auto-WEKA manual.
        weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassif
ier.java:346)
        weka.gui.explorer.AutoWEKAPanel$13.run(AutoWEKAPanel.java:451)

        at weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClas
sifier.java:346)
        at weka.gui.explorer.AutoWEKAPanel$13.run(AutoWEKAPanel.java:451)

OS:win7,weka:3.8,autoweka:2.3

**Comment by jiyonghe** [comment]
JRE and JDK installed and no other issues, use command line "java -jar weka.jar " has the same error

**Comment by larskotthoff** [comment]
Thanks, I'll look into it.

**Comment by larskotthoff** [comment]
This is fixed in 2.4, which should be available shortly.

**Comment by jiyonghe** [comment]
Thanks
