### ISSUE TITLE
FilteredClassifier with autoweka disables CLI only options

### ISSUE THREAD

**Issue by georgejosephada** [larskotthoff/autoweka#47]
As title suggests. I get this error: "Weka exception: Illegal options: -no-cv -split-percentage 66 -no-predictions"

**Comment by larskotthoff** [comment]
How exactly are you running this?

**Comment by georgejosephada** [comment]
Hi Lars,


The command I tried to test is:

java -cp ",;C:\Program Files\Weka-3-8\weka.jar;C:\Users\gjnet\wekafiles\packages\Auto-WEKA\autoweka.jar" weka.classifiers.meta.FilteredClassifier -t "C:\Program Files\Weka-3-8\data\iris.arff" -F "weka.filters.unsupervised.attribute.Remove -R 1" -W weka.classifiers.meta.AutoWEKAClassifier -- -timeLimit 1 -metric areaUnderROC -no-cv -split-percentage 70 -no-predictions


Once I remove these arguments "-no-cv -split-percentage 70 -no-predictions", it works fine


Also, does "-no-predictions" affect autoweka's operation besides conserving memory?


George


________________________________

**Comment by larskotthoff** [comment]
The options "-no-cv -split-percentage 66 -no-predictions" aren't Auto-WEKA options, put them before the -W.

**Comment by georgejosephada** [comment]
Hi Lars,


Fantastic, cheers!


________________________________
