### ISSUE TITLE
2Whomit may concern

### ISSUE THREAD

**Issue by CCMATCH** [larskotthoff/autoweka#53]
Be aware of that In order to use Auto-WEKA through the **WEKA GUI on OSX,** WEKA must be run from the command line instead of the Mac application. For example,
cd /Applications/weka-3-8-1-oracle-jvm.app/Contents/Java/
java -jar weka.jar
Note that Java needs to be installed on your system for this to work. This is because Auto-WEKA needs a java executable to spawn worker processes, and the JRE bundled with the Mac application does not contain one.

**Comment by larskotthoff** [comment]
Thanks, but this is in the manual exactly like this.
