### ISSUE TITLE
Unable to run autoweka with weka experimenter

### ISSUE THREAD

**Issue by pescho** [larskotthoff/autoweka#54]
Hi. I am unable to run autowekaclassifier within weka experimenter. The process always interrupts within a few minutes. The only messages are  "autoweka.Configuration.Collection" followed by  "Interrupted" which is followed by "There was 1 error".  Running with debug set to True does not provide insight. Any insight you might  be able to provide would be greatly appreciated. Thank you!

**Comment by larskotthoff** [comment]
Can you give me some more information about how exactly you're running it? Does it work outside of the experimenter?

**Comment by georgejosephada** [comment]
Had the same issue (Windows x64). Using the JRE provided with the latest stable weka release fixed the issue for me. AutoWEKA refuses to work with Oracle Java 10.
