### ISSUE TITLE
Project containing Run/Compile Errors ( very anoying )

### ISSUE THREAD

**Issue by NickHn94** [larskotthoff/autoweka#55]
Hi,

I downloaded this project and created a new Java Project from Existing Ant Buildfile (), choosed the build.xml in the autoweka-master folder and thought that's it I got the project.

Modyfing AutoWekaPanel:
Reader r = new java.io.BufferedReader(new java.io.FileReader("rec/iris.arff"));
then runing AutoWekaPanel and pressing start.

2017-09-07 13:41:12.928 [Thread-1] WARN Util - Could not auto-detect the location of your Auto-WEKA install - have you moved the classes away from the 'params' diectory?
2017-09-07 13:41:12.931 [Thread-1] WARN ExperimentConstructor - No property file ./autoweka.smac.SMACExperimentConstructor.properties.properties found

I am 100% sure, that I didn't move anything anywhere.
I am 100% sure, that there doesn't exist any SMACExperimentConstructor.properties.properties file in the whole project.

Please could u make your project also accessible for normal humanbeings, it's really frustrating when you need more time to get the project running/compiling than for using. 

Greets, Nick

**Comment by larskotthoff** [comment]
As the warning tells you, you need the "params" directory where you're executing the project. I'm not familiar with Eclipse (is that what you're using?), so I'm afraid I can't help you with the setup there.

Not sure what you mean by your last comment. Of course it'll be more difficult to compile the project than to simply run the pre-compiled code -- for a start, you need a JDK and not just a JRE.
