### ISSUE TITLE
Results doesn't match the corresponding Weka classifier

### ISSUE THREAD

**Issue by renatogbj** [larskotthoff/autoweka#60]
When I run Auto-WEKA and get a result, I try to build the same classifier in regular Weka to see if the results match, but it gives me completely different results.

I tried using the same seed, but results are still very different, going from 10% or even more difference in some metrics.

Also, I tried using the code provided to simulate the classifier in Java and after building the classifier as given, I validate the model like follows:

`Evaluation evaluation = new Evaluation(instances);`
`evaluation.crossValidateModel(classifier, instances, 10, new Random(123));`

It also give me very different results than the shown in Auto-WEKA tab. Is this correct or am I doing something wrong?

Thanks.

**Comment by larskotthoff** [comment]
The data split that you're using to verify is not necessarily the same that Auto-WEKA uses internally to get its performance estimate. This can cause large differences if e.g. you have a relatively small amount of data, or if the data are very varied.

For the best comparability, give both Auto-WEKA and the classifier that you evaluate manually a separate test set.
