### ISSUE TITLE
how to get full report of the auto-weka

### ISSUE THREAD

**Issue by awalece04** [larskotthoff/autoweka#64]
Currently, i can only see best result. That's good. 
But, i want to get full report of the of auto-weka. I mean, results of all classifiers and parameters used in the run.
Thanks in advance. 
Awal
awalece04@yahoo.com

**Comment by larskotthoff** [comment]
The user interface doesn't support getting this information. If you really want to, you can have a look at the internal log files that Auto-WEKA creates in a temporary directory, but these are not in the form of a report at all.
