### ISSUE TITLE
Problem running Auto-Weka : Failed to prepare Experiment

### ISSUE THREAD

**Issue by balacs109** [larskotthoff/autoweka#65]
Hi,

I installed the Auto-Weka recently. The Weka version I have is 3.8.2. However when I try to run through WEKA GUI I get the following error message :
"Problem running Auto-Weka : Failed to prepare Experiment ".

Please help.

Thanks,
Balachandar

**Comment by larskotthoff** [comment]
This may indicate that your disk is full or the temporary directory not writable. How exactly are you running Auto-WEKA?

**Comment by balacs109** [comment]
Hi,

My disk  has lots of free space. I Installed Auto-Weka through the Weka
Manager. I am trying to run the Auto-Weka as instructed in the manual.
Can I know how I would identify the "temp" directory to which it is writing
?

Thanks,
Balachandar

**Comment by larskotthoff** [comment]
What system are you running on? Does Auto-WEKA produce any other kind of output? Can you run other classifiers in WEKA without problems? How big is your dataset?

**Comment by rpcoelho17** [comment]
I'm having the same problem.  Also have lots of space in the hard disk.  Help!

**Comment by larskotthoff** [comment]
You'll have to give me some more information. Just the error message isn't enough to diagnose the problem.
