### ISSUE TITLE
Auto-Weka 2.6.1 not running on Weka 3.8.3

### ISSUE THREAD

**Issue by felipeebert** [larskotthoff/autoweka#68]
Hello, 

I'm trying to run Auto-Weka 2.6.1 on Weka 3.8.3, but it stops running after a few seconds I  click on start button. There is no error message. The only thing we can see is in the log:

15:37:29: Weka Explorer
15:37:29: (c) 1999-2018 The University of Waikato, Hamilton, New Zealand
15:37:29: web: http://www.cs.waikato.ac.nz/~ml/weka/
15:37:29: Started on quarta-feira, 19 setembro 2018
15:37:33: Base relation is now framework-weka.filters.unsupervised.attribute.StringToWordVector-R1-W1000000000-prune-rate-1.0-T-I-N0-L-stemmerweka.core.stemmers.SnowballStemmer-stopwords-handlerweka.core.stopwords.Rainbow-M1-tokenizerweka.core.tokenizers.NGramTokenizer -max 2 -min 1 -delimiters " \r\n\t.,;:\'\"()?!"-weka.filters.unsupervised.attribute.Remove-V-R6,28,96,544,649,707-709,772,819,1251,1346,1725,1961,2004,2007,2031,2106,2353,2359,2368,2381,2431,2553,2570,2860,2950,2998,3109,3134,3139,3152,3221,3347,3378,3460,3492,3494,3763,3956,4078,4252,4289,4539,4723,4842,5245,5313,5466,5559,5568,5617,5633,5732,5859,5913,6095,6137,6201,6456,6464,6585,6763,6769,6776,6779,6816,6838,6840,6842,6848,6850,6855,6862,6865,6868,6977,7001,7037,7058,8869,9554,12176,14703,15043,15830,18813,18924,19979,20783,21108,21216,22206,710-weka.filters.supervised.instance.StratifiedRemoveFolds-S0-N10-F1 (833 instances)
15:37:33: java.lang.NullPointerException
15:37:47: Started Auto-WEKA for framework-weka.filters.unsupervised.attribute.StringToWordVector-R1-W1000000000-prune-rate-1.0-T-I-N0-L-stemmerweka.core.stemmers.SnowballStemmer-stopwords-handlerweka.core.stopwords.Rainbow-M1-tokenizerweka.core.tokenizers.NGramTokenizer -max 2 -min 1 -delimiters " \r\n\t.,;:\'\"()?!"-weka.filters.unsupervised.attribute.Remove-V-R6,28,96,544,649,707-709,772,819,1251,1346,1725,1961,2004,2007,2031,2106,2353,2359,2368,2381,2431,2553,2570,2860,2950,2998,3109,3134,3139,3152,3221,3347,3378,3460,3492,3494,3763,3956,4078,4252,4289,4539,4723,4842,5245,5313,5466,5559,5568,5617,5633,5732,5859,5913,6095,6137,6201,6456,6464,6585,6763,6769,6776,6779,6816,6838,6840,6842,6848,6850,6855,6862,6865,6868,6977,7001,7037,7058,8869,9554,12176,14703,15043,15830,18813,18924,19979,20783,21108,21216,22206,710-weka.filters.supervised.instance.StratifiedRemoveFolds-S0-N10-F1

I tried it either on Auto-Weka panel and also on Classify panel. I already tried to uninstall and install Auto-Weka on Weka. I'm using Windows 10. 

Thank you in advance.

**Comment by larskotthoff** [comment]
It looks like you have a lot of data, so that might cause memory errors. Have you tried running a "normal" WEKA classifier?
