### ISSUE TITLE
"Problem running AutoWeka: null" when metric is areaAboveROC/areaUnderRoc

### ISSUE THREAD

**Issue by tsiakmaki** [larskotthoff/autoweka#73]
i am getting the 
`Problem running AutoWeka: null`
for an imbalanced dataset, on which i set the metric to `areaAboveROC` or `areaUnderRoc`. 
The logs are like: 
```
14:15:34: Thread 0: performed 10 evaluations, estimated areaAboveROC 5.0E99...
14:15:42: Thread 0: performed 20 evaluations, estimated areaAboveROC 4.285714285714286E99...
14:15:48: Thread 0: performed 30 evaluations, estimated areaAboveROC 3.7500000000000003E99...
14:15:57: Thread 0: performed 40 evaluations, estimated areaAboveROC 4.444444444444445E99...
14:16:02: Thread 0: performed 50 evaluations, estimated areaAboveROC 4.0000000000000004E99...
14:16:10: Thread 0: performed 60 evaluations, estimated areaAboveROC 4.0000000000000004E99...
14:16:18: null
```
Isn't the returned areaAboveROC realy odd? 
I have run this dataset with `errorRate`, and other imbalanced datasets with no problem.

**Comment by larskotthoff** [comment]
Can you please provide a complete example that allows to reproduce the problem? How you're running Auto-WEKA, settings, data.
