### ISSUE TITLE
AutoWeka should be updated?

### ISSUE THREAD

**Issue by celestinoxp** [larskotthoff/autoweka#79]
Today Weka's development team announced the new versions and the new use of Java 11.
See: https://weka.8497.n7.nabble.com/New-releases-of-WEKA-3-8-4-and-3-9-4-tp45978.html

As we know the AutoWeka package uses Java 8, which may require us to have 2 versions of Java on the PC, but I think we should keep up with the full potential of the new version of Java 11.

So can developers upgrade the AutoWeka package to use Java 11?

**Comment by larskotthoff** [comment]
Have you tried running it with Java 11?

**Comment by celestinoxp** [comment]
> Você já tentou executá-lo com o Java 11?

Yes, and not works....So i installed java 8, again :)

> There are currently two packages that cannot be used with these new platform-specific distributions of WEKA: the tigerJython package and the Auto-WEKA package. The reason for this is that they currently cannot be run with a Java 11 JVM.

You can confim here: https://weka.8497.n7.nabble.com/New-releases-of-WEKA-3-8-4-and-3-9-4-td45978.html

**Comment by larskotthoff** [comment]
Ok, thanks for the report. I don't have the resources to look into this right now, but might come back to this later.

**Comment by celestinoxp** [comment]
> Ok, thanks for the report. I don't have the resources to look into this right now, but might come back to this later.

I think interesting introducing some new updates in AutoWeka package.
- Possibility of choose the algorithm to test all hyperparameters.
- Introduce some modifications in test algorithm hyperparameters, like more different hiddenlayers when autoweka uses multilayerperceptron, example accept choise to add range of hiddenlayers, ex 1 to 100 or more layers example triple layers, 10,8,9. (actually uses only parameters: a, i, o, t )

-In weka filters it is possible to create new attributes using mathematical expressions, however the effectiveness may have no impact. The Autoweka package should automatically create virtual attributes to improve efficiency.

- Finally i think its interesting create a discussion about the advantages of updating Autoweka package. I have a lot of ideas :)

**Comment by larskotthoff** [comment]
Pull requests are always welcome :)
