### ISSUE TITLE
No results hours after timelimit.

### ISSUE THREAD

**Issue by msudol** [larskotthoff/autoweka#81]
I ran Auto-WEKA for 5 hours, it's been 10 and the outpout window is blank, and the little bird icon is no longer moving.  I had debug on to produce extra output..  in the log I have this.  

`03:01:56: Started Auto-WEKA for csic_emcl_final-weka.filters.unsupervised.attribute.Reorder-R2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,1
04:02:48: Thread 0: performed 10 evaluations, estimated errorRate 0.2176897519570428...
04:18:36: Thread 0: performed 20 evaluations, estimated errorRate 0.2181573865317917...
04:27:12: Thread 3: performed 10 evaluations, estimated errorRate 0.19944824485336018...
07:12:49: Thread 3: performed 20 evaluations, estimated errorRate 0.18012724334354205...`

My run configuration is this:  

`weka.classifiers.meta.AutoWEKAClassifier -seed 123 -timeLimit 300 -memLimit 4096 -nBestConfigs 5 -metric errorRate -parallelRuns 4 -output-debug-info -batch-size 1000`

Is there a way to stop and get the results, the "stop" option is greyed out?  Is it already stopped, my CPU and RAM utilization are down to the normal baseline - in all it appears the process has completed and simply generated no results for me?  Seems wrong based on the log.  Suggestions?

**Comment by msudol** [comment]
Issue turns out to be RAM related - the result buffer wasn't printing, however no message or log information was displayed to notify end user of the failure.  Increases allocated memory on startup resolved the initial problem, however a bug remains such that there is no user notification of the failure.

**Comment by larskotthoff** [comment]
This is a difficult one unfortunately because for memory issues Auto-WEKA may not get any indication that something has gone wrong -- for example the garbage collector may simply be running pretty much all the time. Or a sub-process may simply go away without any indication that anything has gone wrong.

Suggestions of course appreciated, but I'm not aware of a way of doing this reliably.

**Comment by msudol** [comment]
Thinking about it some more, it's more of a Weka bug that an Auto-WEKA bug. I ran into a similar issue just doing a standard (long running) classification where the process completed or hung and nothing was in the log buffer. I'd think something like that could get punted off to a tmp log file, instead it looks like its cached in mem. You can close this, I'd say, because you've just inherited the issue from Weka and it's not specific to AW.

**Comment by larskotthoff** [comment]
Thanks will do -- I agree that WEKA's handling of this could be better, but of course temporary files come with their own complications, so I can see why they implemented it this way.

All in all, once you run out of memory, pretty much all bets are off.
