### ISSUE TITLE
Choose range of attributes number

### ISSUE THREAD

**Issue by Lijingzzu** [larskotthoff/autoweka#82]
Is it possible to choose the range of attributes number in autoweka? For instance, I have 3000 attributes, but I want to know the best 10-20 attributes which can predict the classify.

**Comment by larskotthoff** [comment]
For this you should use one of the feature selection methods in WEKA, not Auto-WEKA.

**Comment by Lijingzzu** [comment]
Many thanks for your reply! 
If I don't know which attribute evaluator and search method is the best, and I want to know the accuracy of 10-20 attributes. Should I try all the combinations or is there a good way to run it automatically?
