### ISSUE TITLE
Select attributes

### ISSUE THREAD

**Issue by Lijingzzu** [larskotthoff/autoweka#83]
I don't know which attribute evaluator and search method is the best, and I want to know the performance of the best 10-30 attributes out of 3000. Should I try all the combinations or is there a good way to run it automatically? Many thanks!

**Comment by larskotthoff** [comment]
This is something that you can't really do automatically because it depends on your definition of "best" -- do you want the fewest attributes, or the best performance? If the latter, it makes most sense to just run Auto-WEKA and not worry about whether attribute selection is performed explicitly or not.

**Comment by Lijingzzu** [comment]
Thanks for your answer!
The performance is more important for me. But 3000 attributes is also quite a lot for further investigation. I hope to find the best performance in a range of the number of attributes, for instance, 10-30 attributes. Is there a way to test all the Select attribute algorithm combinations on a defined range of the number of attributes?

**Comment by larskotthoff** [comment]
No, unfortunately not. I would pre-filter the attributes before giving the data to Auto-WEKA.

**Comment by Lijingzzu** [comment]
Thank you very much!
I tried many combinations in the Select attribute, but every time I got different attributes according to different methods. 
I also noticed that in the Select attribute tab there is an option called ClassifierAttributeEval in which you can choose AutoWEKA as the classifier. I tried several times, but the outcome was always that my computer took several hours to run and crushed at the end. Do you think it is possible to run this scheme?

**Comment by larskotthoff** [comment]
It doesn't make sense to run Auto-WEKA in the ClassifierAttributeEval, but unfortunately there's no way to prevent this in the Auto-WEKA code. And yes, you'll get different results with different methods -- this is where I would recommend a domain expert to have a look at it to see which ones make most sense.

**Comment by Lijingzzu** [comment]
OK. Again thanks a lot for your kind consideration!
