### ISSUE TITLE
Error running Auto-Weka

### ISSUE THREAD

**Issue by delreal90** [larskotthoff/autoweka#85]
I'm having problems running Auto-Weka in a new machine I bought a few months ago. Before that, I have used Auto-Weka in several computers without any problem.

In the new one I got an error saying "Problem running AUto-WEKA: java.lang.RuntimeException: Error marshalling XML response"

So far I have tried installing JAVA 8, or installing JVK 1.8, but I keep getting the same error.

Thank you for all the help

**Comment by larskotthoff** [comment]
Have you tried the solution mentioned in #20 ?

**Comment by delreal90** [comment]
Thank you Lars for your answer!

It kind of was above my knowledge, but looking that issue and others I found out that I was using WEKA 3.8.4 and Java 11, so what I did was to uninstall WEKA and Java, and then reinstall WEKA 3.8.3 and Java 8, which solved the issue! I hope my answer will be useful for someone else.

**Comment by larskotthoff** [comment]
Great, glad you got it to work!
