### ISSUE TITLE
Error marshalling xml response

### ISSUE THREAD

**Issue by Speeskees** [larskotthoff/autoweka#87]
I've tried to run Auto-Weka using the Auto-Weka tab in the explorer GUI, but it throws a runtime exception: Error marshalling xml reponse. I'm running Weka 3.8.4 with the most recent Auto-Weka, installed from the package explorer. I've tried using OpenJDK 8, 11 and 14, but all throw the same exception. Lastly, I'm running Windows 10 2004. Google isn't helpful either.

**Comment by larskotthoff** [comment]
Have you seen #85 ?

**Comment by celestinoxp** [comment]
why does autoweka package not receive new updates?
Support for java 11 is an idea ...

**Comment by larskotthoff** [comment]
Pull requests welcome :)

**Comment by celestinoxp** [comment]
I'm not a java programmer... :( Why you don't do somehting (small updates) ?

**Comment by larskotthoff** [comment]
I simply don't have the time unfortunately. There's a chance that it would be only small changes, but it could also be substantial changes.

**Comment by ivanfalconi** [comment]
Hi. Is there a solution for the error message "java.lang.RuntimeException: Error marshelling XML response" when running autoWeka? Please, advice.

Thanks
