### ISSUE TITLE
Description of Parameter Dialect

### ISSUE THREAD

**Issue by sherbold** [larskotthoff/autoweka#88]
Cool package!

I am trying to read the parameter combinations, because I would like to know which values exactly you are using for the random forest. I assume this is based on the [params/base/weka.classifiers.trees.RandomForest.params](../blob/master/params/base/weka.classifiers.trees.RandomForest.params) file. 

However, I am not quite sure how to read that. From the JLMR paper, I think I should get seven combinations, but I do not understand how this works without a deep dive into the parsing code. Do you have a short explanation, or maybe just the of the RandomForest for me?

**Comment by larskotthoff** [comment]
The format is the one used by SMAC -- each line is a parameter (7 before the conditionals) and the first set of numbers after the parameter name gives the range of values with the default after that. The specific notation and characters at the end denote discrete vs continuous values etc.

The conditionals specify which parameters must be set to specific values if certain parameters are used.
